### ISSUE TITLE
 el6 rpms missing execute permission on /etc/rc.d/init.d/*_exporter

### ISSUE THREAD

**Issue by ncamx** [lest/prometheus-rpm#81]
Unsure whether this is something odd in the binary rpms or caused by something odd about my target:

\# uname -a
Linux xxxx 2.6.32-358.el6.x86_64

\# rpm -i pkgs/node_exporter-0.17.0-1.el6.x86_64.rpm

\# rpm -q --list node_exporter-0.17.0 | xargs ls -ld
-rw-r--r--. 1 root       root              0 Dec 27 09:19 /etc/default/node_exporter
-rw-r--r--. 1 root       root           1808 Dec 27 09:19 /etc/rc.d/init.d/node_exporter  **### <======== rw only**
-rwxr-xr-x. 1 root       root       12325410 Dec 27 09:19 /usr/bin/node_exporter
drwxr-xr-x. 2 prometheus prometheus     4096 Dec 27 09:19 /var/lib/prometheus

rpm -i --noscripts = same result  i.e. 644

From spec.tpl though, it's hard to see why this wouldn't end up 755? Tried other (postgres) exporters and older exporters for comparison and  init.d entry was always 644. Any ideas?

**Comment by britcey** [comment]
Somewhat my fault - I fixed the template.spec when I was fixing the Redis exporter but failed to mention it / call it out in a separate commit:

https://github.com/lest/prometheus-rpm/commit/4035ef0e4e212d398518def2eb8e05a0aef2a123#diff-f330955ca6ef92f96f92e832cd10fbbaL57

So packages built since that merge should have the correct permissions.

I don't know if the packages should be rebuilt w/ a new package release number or wait for the next round of exporter updates.

**Comment by ncamx** [comment]
Thanks for that clarification - makes sense now. Easy enough to work around in the meantime.
